// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMQdHtdlVhACTX6Cs1DrKxu94fPQo9yaM',
    appId: '1:1069139805657:web:62f5b676ac0209d60ac5c8',
    messagingSenderId: '1069139805657',
    projectId: 'chat-app-d6f2a',
    authDomain: 'chat-app-d6f2a.firebaseapp.com',
    storageBucket: 'chat-app-d6f2a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ89OmKy1UBK-nVKitKqyucM0jc9zsH3M',
    appId: '1:1069139805657:android:f94f11481cb3b3810ac5c8',
    messagingSenderId: '1069139805657',
    projectId: 'chat-app-d6f2a',
    storageBucket: 'chat-app-d6f2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaKJNrJneuS4fqArCqiavRHZp_gFtv4_Q',
    appId: '1:1069139805657:ios:4969ec2bab12d7a00ac5c8',
    messagingSenderId: '1069139805657',
    projectId: 'chat-app-d6f2a',
    storageBucket: 'chat-app-d6f2a.firebasestorage.app',
    iosBundleId: 'com.example.chatBox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaKJNrJneuS4fqArCqiavRHZp_gFtv4_Q',
    appId: '1:1069139805657:ios:4969ec2bab12d7a00ac5c8',
    messagingSenderId: '1069139805657',
    projectId: 'chat-app-d6f2a',
    storageBucket: 'chat-app-d6f2a.firebasestorage.app',
    iosBundleId: 'com.example.chatBox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMQdHtdlVhACTX6Cs1DrKxu94fPQo9yaM',
    appId: '1:1069139805657:web:d2899f71d57170a60ac5c8',
    messagingSenderId: '1069139805657',
    projectId: 'chat-app-d6f2a',
    authDomain: 'chat-app-d6f2a.firebaseapp.com',
    storageBucket: 'chat-app-d6f2a.firebasestorage.app',
  );
}
